version: "3.9"
services:
  app:
    depends_on:
      - mysql
    build:
      dockerfile: dev.Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - "80:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: viki

  mysql:
    image: mysql:5.7
    volumes:
      - viki-mysql-data:/var/lib/mysql
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/migrate.sql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: viki
    ports:
      - "3306:3306"
volumes:
  viki-mysql-data:
